my_string = input('Your text: ')
print('Символов в напечатанном тексте:', len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])